/*
 * Author:  Douglas
 * Created: 09/07/2021
 */

--  SQL to MYSQL
CREATE DATABASE DATABASE_AGENDA;
USE DATABASE_AGENDA;
-- IF APP NOT OPEN; USE
SET GLOBAL time_zone = '-3:00';

CREATE TABLE EVENT (
	ID_EVENT INT AUTO_INCREMENT,
	NAME VARCHAR(120) NOT NULL,
	CONSTRAINT UQ_EVENT_NAME UNIQUE (NAME),
	PRIMARY KEY (ID_EVENT)
);

CREATE TABLE DISCIPLINE (
	ID_DISCIPLINE INT AUTO_INCREMENT,
	NAME VARCHAR(120) NOT NULL,
	CONSTRAINT UQ_DISCIPLINE_NAME UNIQUE (NAME), 
    PRIMARY KEY (ID_DISCIPLINE)
    );

CREATE TABLE TIME(
	ID_TIME INT AUTO_INCREMENT,
	TIME VARCHAR(20) NOT NULL,
	CONSTRAINT UQ_TIME_TIME UNIQUE (TIME),
	PRIMARY KEY (ID_TIME)    
);

CREATE TABLE ACADEMIC_AGENDA (
	ID_AGENDA INT AUTO_INCREMENT,
	ID_EVENT INT,
	ID_DISCIPLINE INT,
	ID_TIME INT,
	DAYS DATE NOT NULL,
	NOTE VARCHAR(300),
	FOREIGN KEY (ID_EVENT) REFERENCES EVENT (ID_EVENT),
	FOREIGN KEY (ID_DISCIPLINE) REFERENCES DISCIPLINE (ID_DISCIPLINE),
	FOREIGN KEY (ID_TIME) REFERENCES TIME (ID_TIME),
	CONSTRAINT UQ_AGENDA_DAYS_TIME UNIQUE (DAYS,ID_TIME),
	PRIMARY KEY (ID_AGENDA, ID_TIME, DAYS)
);

INSERT INTO EVENT (ID_EVENT, NAME) VALUES (1,'AVALIAÇÃO.');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (2,'AVALIAÇÃO COM CONSULTA.');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (3,'AVALIAÇÃO ORAL.');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (4,'COMEMORAÇÃO.');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (5,'INICIAÇÃO CIENTÍFICA.');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (6,'MONITORIA.');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (7,'PALESTRA.');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (8,'TCC 1');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (9,'TCC 2');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (10,'TCC 3');
INSERT INTO EVENT (ID_EVENT, NAME) VALUES (11,'TRABALHO.');

INSERT INTO DISCIPLINE (ID_DISCIPLINE, NAME) VALUES (1,'ESTATÍSTICA DESCRITIVA.');
INSERT INTO DISCIPLINE (ID_DISCIPLINE, NAME) VALUES (2,'ESTRUTURA DE DADOS.');
INSERT INTO DISCIPLINE (ID_DISCIPLINE, NAME) VALUES (3,'FUNDAMENTOS DE GESTÃO DE TI.');
INSERT INTO DISCIPLINE (ID_DISCIPLINE, NAME) VALUES (4,'FUNDAMENTOS DE REDES DE COMPUTADORES.');
INSERT INTO DISCIPLINE (ID_DISCIPLINE, NAME) VALUES (5,'INGLÊS III');
INSERT INTO DISCIPLINE (ID_DISCIPLINE, NAME) VALUES (6,'LABORATÓRIO DE DESENV. EM BD 3');
INSERT INTO DISCIPLINE (ID_DISCIPLINE, NAME) VALUES (7,'LINGUAGEM DE PROGRAMAÇÃO II');
INSERT INTO DISCIPLINE (ID_DISCIPLINE, NAME) VALUES (8,'PROGRAMAÇÃO DE BANCO DE DADOS');

INSERT INTO TIME (ID_TIME, TIME) VALUES (1,'1ªClass Morning');
INSERT INTO TIME (ID_TIME, TIME) VALUES (2,'2ªClass Morning');
INSERT INTO TIME (ID_TIME, TIME) VALUES (3,'Interval Morning');
INSERT INTO TIME (ID_TIME, TIME) VALUES (4,'3ªClass Morning');
INSERT INTO TIME (ID_TIME, TIME) VALUES (5,'4ªClass Morning');
INSERT INTO TIME (ID_TIME, TIME) VALUES (6,'1ªClass Afternoon');
INSERT INTO TIME (ID_TIME, TIME) VALUES (7,'2ªClass Afternoon');
INSERT INTO TIME (ID_TIME, TIME) VALUES (8,'Interval Afternoon');
INSERT INTO TIME (ID_TIME, TIME) VALUES (9,'3ªClass Afternoon');
INSERT INTO TIME (ID_TIME, TIME) VALUES (10,'4ªClass Afternoon');
INSERT INTO TIME (ID_TIME, TIME) VALUES (11,'1ªClass Night');
INSERT INTO TIME (ID_TIME, TIME) VALUES (12,'2ªClass Night');
INSERT INTO TIME (ID_TIME, TIME) VALUES (13,'Interval Night');
INSERT INTO TIME (ID_TIME, TIME) VALUES (14,'3ªClass Night');
INSERT INTO TIME (ID_TIME, TIME) VALUES (15,'4ªClass Night');

/*
INSERT INTO TIME (ID_TIME, TIME) VALUES (1,'00:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (2,'01:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (3,'02:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (4,'03:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (5,'04:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (6,'05:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (7,'06:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (8,'07:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (9,'08:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (10,'09:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (11,'10:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (12,'11:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (13,'12:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (14,'13:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (15,'14:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (16,'15:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (17,'16:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (18,'17:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (19,'18:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (20,'19:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (21,'20:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (22,'21:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (23,'22:00 H');
INSERT INTO TIME (ID_TIME, TIME) VALUES (24,'23:00 H');
*/